---
version: "3.4"
services:
  weaviate:
    command:
    - --host
    - 0.0.0.0
    - --port
    - "8080"
    - --scheme
    - http
    image: semitechnologies/weaviate:1.19.5
    ports:
    - 8080:8080
    restart: on-failure:0
    volumes:
      - ./data:/var/lib/weaviate
    environment:
      QUERY_DEFAULTS_LIMIT: 25
      AUTHENTICATION_ANONYMOUS_ACCESS_ENABLED: "true"
      PERSISTENCE_DATA_PATH: "/var/lib/weaviate"
      CLUSTER_HOSTNAME: "node1"
      OPENAI_APIKEY: "${OPENAI_APIKEY}"
      DEFAULT_VECTORIZER_MODULE: "text2vec-openai"
      ENABLE_MODULES: "text2vec-openai,generative-openai"
...